### ISSUE TITLE
Mysql installation error 

### ISSUE THREAD

**Issue by Releasement** [nashikouen/kotatsuBBS#1]
When i try to run the install.php it shows a page saying

>  "it seems this has already been installed. if this is a issue, edit your conf.php to valid credentals, or delete conf.php and run this php file again"

**Comment by chen-chan1** [comment]
i didnt expect some one to try running this yet.. i have not made a proper release, there is no admin panel to deal with spam.

at the top of the install page it has this 

```
<?php
if(file_exists(__DIR__ . "/conf.php")){
    echo "it seems this has already been installed. if this is a issue, edit your conf.php to valid credentals, or delete conf.php and run this php file again";
    die();
}
```
this must mean you already have a conf.php in your system directory.
i guess example is a bad name since it dose not actualy set up tables and stuff in the data base. so cahnge it back to example.conf.php and run install script, it will auto make a conf.php

**Comment by chen-chan1** [comment]
i better clarified the names so this wont be a future issue. 

embedding it into install.php would make it harder for development and harder for sysadmin to understand there curent configs as it strips everything with vardump

**Comment by chen-chan1** [comment]
oh i guess i forgot to mentions i "fixed" it in the new push, meaning it just has better names to stop user error. just re install with mysql and you are good. make a new issue if you run into anything i will keep a eye on this now.
if you would like to see what it looks like here is my test server http://45.76.13.45/intro/

**Comment by Releasement** [comment]
Ah okay. I ended up just replacing [`if(file_exists(__DIR__ . "/conf.php")){` with example.config.php and that got me past the installer, couldn't get father than that though. 

I'd like to add some ubuntu install instructions once I can get it running, are you ok with that?

**Comment by chen-chan1** [comment]
some time in june this will be at a state for a release. i have a debian server running  [this](https://github.com/Heyuri/kokonotsuba)
one place where i chat on about software dev you might catch me or some other guy who helps would be [here](https://cgi.heyuri.net/chat/)
